services:
  servidor2:
    build: 
      context: ./servidor/main
      dockerfile: Dockerfile
    container_name: servidor2
    ports:
      - "8082:8082"
    environment:
      - ID=002
      - PORTA=8082
    volumes:
      - ./dados/empresas.json:/app/empresas.json
      - ./dados/regiao.json:/app/regiao.json
      - ./dados/veiculos.json:/app/veiculos.json
